# Generated by Django 4.2 on 2023-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_bloguser_avatar_alter_bloguser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar/blank-profile-picture.png', upload_to='avatars/'),
        ),
    ]
